@extends('layouts.main')
@section ('breadcrumb')
    <button type="button" class="btn round-btn pull-right c-grey" data-toggle="modal" data-target="#help">
        <i class="fa fa-question fa-lg" aria-hidden="true"></i>
    </button>
    {!! Breadcrumbs::render('home') !!}
@endsection

@section('content')
    <!-- Modal -->
    <div id="help" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Help File</h4>
                </div>
                <div class="modal-body">
                    <h3>Getting Started</h3>
                    <h4>Step 1 - Add Workspaces</h4>
                    <p>A Workspace is a collection of Applications, Folders and Files. To add your Workspace, click "Add Workspace" and
                    provide a Title and Description. Click Submit to continue.</p>
                    <h4>Step 2 - Add Applications</h4>
                    <p>Select your newly created Workspace and choose your Application by clicking on "Add Application". Provide
                        a Title and Description and click Submit to continue.
                    <h4>Step 3 - Add Folders</h4>
                    <p>Folders are used to store vulnerability record data that is relevant to your Workspace and Applications.
                    To add a Folder, click "Add Folder" in your Workspace and provide a Title and Description. Click Submit to continue.</p>
                    <h4>Step 4 - Add Files</h4>
                    <p>Files are the actual XML reports generated by the various scanners that are uploaded and
                    associated with a Workspace. To create a File, select your Application and click "Add File".
                        Provide a Title, Description and XML file. Click Submit to upload the file.</p>
                    <h4>Step 5 - View and Manage Vulnerabilities</h4>
                    <p>Select your File and interact with the relevant vulnerability data. Vulnerability records can
                    be added to a Folder or sent to JIRA.</p>
                </div>
            </div>

        </div>
    </div>
    <div class="row animated fadeIn">
        <div class="col-md-12">
            @can (App\Policies\ComponentPolicy::ACTION_CREATE, new App\Entities\Workspace())
                <a href="{{ route('workspace.create') }}" class="primary-btn" type="button">Add Workspace</a>
            @endcan
        </div>
    </div>
    <div class="row animated fadeIn">
        <ul class=tabs>
            <li>
                @include('partials.workspaces-tab', ['tabNo' => 1])
            </li>
        </ul>
        <br style=clear:both;>
    </div>
@endsection
