<?php

use App\Utils\RawMigration;

class CreateAuditsTable extends RawMigration
{
    /**
     * @inheritdoc
     * @return string
     */
    public function getRawSqlMigration()
    {
        return <<<SQL
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS `audits` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `audit_file` VARCHAR(150) NULL DEFAULT NULL COMMENT '',
  `compliance_check_name` TEXT NULL DEFAULT NULL COMMENT '',
  `compliance_check_id` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `actual_value` TEXT NULL DEFAULT NULL COMMENT '',
  `policy_value` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `info` TEXT NULL DEFAULT NULL COMMENT '',
  `result` ENUM('PASSED', 'FAILED', 'ERROR', 'WARNING') NULL DEFAULT NULL COMMENT '',
  `reference` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `see_also` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `description` TEXT NULL DEFAULT NULL COMMENT '',
  `solution` TEXT NULL DEFAULT NULL COMMENT '',
  `agent` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `uname` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `output` TEXT NULL DEFAULT NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `assets_audits` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `asset_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  `audit_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE KEY `assets_audits_idx` (`asset_id`, `audit_id`),
  CONSTRAINT `assets_audits_asset_fk` FOREIGN KEY (`asset_id`)
    REFERENCES `assets` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `assets_audits_audit_fk` FOREIGN KEY (`audit_id`)
    REFERENCES `audits` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `files_audits` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `file_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  `audit_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE KEY `files_audits_idx` (`file_id`, `audit_id`),
  CONSTRAINT `files_audits_file_fk` FOREIGN KEY (`file_id`)
    REFERENCES `files` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `files_audits_audit_fk` FOREIGN KEY (`audit_id`)
    REFERENCES `audits` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
SQL;
    }
}
